export const SYMBOLS = [
  "BTCUSDT",
  "ETHUSDT",
  "SOLUSDT",
  "ADAUSDT",
  "DOTUSDT",
  "BCHUSDT",
  "QNTUSDT",
] as const;

export type Symbol = (typeof SYMBOLS)[number];

export const INTERVALS = ["1s", "5s", "1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w"] as const;
export type Interval = (typeof INTERVALS)[number];

// Coin metadata type used for both default and user-added coins
export interface CoinConfig {
  pair: string;      // e.g. "BTCUSDT"
  ticker: string;    // e.g. "BTC"
  name: string;      // e.g. "Bitcoin"
}

// Default coins for new users (kept small — users can add more)
export const DEFAULT_COINS: CoinConfig[] = [
  { pair: "BTCUSDT", ticker: "BTC", name: "Bitcoin" },
  { pair: "ETHUSDT", ticker: "ETH", name: "Ethereum" },
  { pair: "LTCUSDT", ticker: "LTC", name: "Litecoin" },
];

// Top 200+ coins by market cap (Binance USDT pairs)
export const COIN_CATALOG: CoinConfig[] = [
  { pair: "BTCUSDT", ticker: "BTC", name: "Bitcoin" },
  { pair: "ETHUSDT", ticker: "ETH", name: "Ethereum" },
  { pair: "BNBUSDT", ticker: "BNB", name: "BNB" },
  { pair: "SOLUSDT", ticker: "SOL", name: "Solana" },
  { pair: "XRPUSDT", ticker: "XRP", name: "Ripple" },
  { pair: "DOGEUSDT", ticker: "DOGE", name: "Dogecoin" },
  { pair: "ADAUSDT", ticker: "ADA", name: "Cardano" },
  { pair: "TRXUSDT", ticker: "TRX", name: "TRON" },
  { pair: "AVAXUSDT", ticker: "AVAX", name: "Avalanche" },
  { pair: "LINKUSDT", ticker: "LINK", name: "Chainlink" },
  { pair: "SHIBUSDT", ticker: "SHIB", name: "Shiba Inu" },
  { pair: "DOTUSDT", ticker: "DOT", name: "Polkadot" },
  { pair: "BCHUSDT", ticker: "BCH", name: "Bitcoin Cash" },
  { pair: "SUIUSDT", ticker: "SUI", name: "Sui" },
  { pair: "LTCUSDT", ticker: "LTC", name: "Litecoin" },
  { pair: "NEARUSDT", ticker: "NEAR", name: "NEAR Protocol" },
  { pair: "UNIUSDT", ticker: "UNI", name: "Uniswap" },
  { pair: "APTUSDT", ticker: "APT", name: "Aptos" },
  { pair: "ICPUSDT", ticker: "ICP", name: "Internet Computer" },
  { pair: "ETCUSDT", ticker: "ETC", name: "Ethereum Classic" },
  { pair: "RENDERUSDT", ticker: "RENDER", name: "Render" },
  { pair: "PEPEUSDT", ticker: "PEPE", name: "Pepe" },
  { pair: "XLMUSDT", ticker: "XLM", name: "Stellar" },
  { pair: "ATOMUSDT", ticker: "ATOM", name: "Cosmos" },
  { pair: "FILUSDT", ticker: "FIL", name: "Filecoin" },
  { pair: "ARBUSDT", ticker: "ARB", name: "Arbitrum" },
  { pair: "INJUSDT", ticker: "INJ", name: "Injective" },
  { pair: "OPUSDT", ticker: "OP", name: "Optimism" },
  { pair: "VETUSDT", ticker: "VET", name: "VeChain" },
  { pair: "ALGOUSDT", ticker: "ALGO", name: "Algorand" },
  { pair: "FTMUSDT", ticker: "FTM", name: "Fantom" },
  { pair: "AAVEUSDT", ticker: "AAVE", name: "Aave" },
  { pair: "QNTUSDT", ticker: "QNT", name: "Quant" },
  { pair: "GRTUSDT", ticker: "GRT", name: "The Graph" },
  { pair: "MATICUSDT", ticker: "MATIC", name: "Polygon" },
  { pair: "THETAUSDT", ticker: "THETA", name: "Theta Network" },
  { pair: "SANDUSDT", ticker: "SAND", name: "The Sandbox" },
  { pair: "MANAUSDT", ticker: "MANA", name: "Decentraland" },
  { pair: "AXSUSDT", ticker: "AXS", name: "Axie Infinity" },
  { pair: "EOSUSDT", ticker: "EOS", name: "EOS" },
  { pair: "MKRUSDT", ticker: "MKR", name: "Maker" },
  { pair: "SNXUSDT", ticker: "SNX", name: "Synthetix" },
  { pair: "XTZUSDT", ticker: "XTZ", name: "Tezos" },
  { pair: "NEOUSDT", ticker: "NEO", name: "Neo" },
  { pair: "FLOWUSDT", ticker: "FLOW", name: "Flow" },
  { pair: "EGLDUSDT", ticker: "EGLD", name: "MultiversX" },
  { pair: "APEUSDT", ticker: "APE", name: "ApeCoin" },
  { pair: "CHZUSDT", ticker: "CHZ", name: "Chiliz" },
  { pair: "COMPUSDT", ticker: "COMP", name: "Compound" },
  { pair: "LDOUSDT", ticker: "LDO", name: "Lido DAO" },
  { pair: "RNDRUSDT", ticker: "RNDR", name: "Render Token" },
  { pair: "RUNEUSDT", ticker: "RUNE", name: "THORChain" },
  { pair: "IOTAUSDT", ticker: "IOTA", name: "IOTA" },
  { pair: "ZILUSDT", ticker: "ZIL", name: "Zilliqa" },
  { pair: "ENAUSDT", ticker: "ENA", name: "Ethena" },
  { pair: "WLDUSDT", ticker: "WLD", name: "Worldcoin" },
  { pair: "PENDLEUSDT", ticker: "PENDLE", name: "Pendle" },
  { pair: "TIAUSDT", ticker: "TIA", name: "Celestia" },
  { pair: "SEIUSDT", ticker: "SEI", name: "Sei" },
  { pair: "JUPUSDT", ticker: "JUP", name: "Jupiter" },
  { pair: "STXUSDT", ticker: "STX", name: "Stacks" },
  { pair: "CFXUSDT", ticker: "CFX", name: "Conflux" },
  { pair: "WIFUSDT", ticker: "WIF", name: "dogwifhat" },
  { pair: "FLOKIUSDT", ticker: "FLOKI", name: "FLOKI" },
  { pair: "BONKUSDT", ticker: "BONK", name: "Bonk" },
  { pair: "DYDXUSDT", ticker: "DYDX", name: "dYdX" },
  { pair: "FETUSDT", ticker: "FET", name: "Fetch.ai" },
  { pair: "AGIXUSDT", ticker: "AGIX", name: "SingularityNET" },
  { pair: "OCEANUSDT", ticker: "OCEAN", name: "Ocean Protocol" },
  { pair: "CRVUSDT", ticker: "CRV", name: "Curve DAO" },
  { pair: "1INCHUSDT", ticker: "1INCH", name: "1inch" },
  { pair: "LRCUSDT", ticker: "LRC", name: "Loopring" },
  { pair: "ENSUSDT", ticker: "ENS", name: "Ethereum Name Service" },
  { pair: "KSMUSDT", ticker: "KSM", name: "Kusama" },
  { pair: "GALAUSDT", ticker: "GALA", name: "Gala" },
  { pair: "IMXUSDT", ticker: "IMX", name: "Immutable" },
  { pair: "SKLUSDT", ticker: "SKL", name: "SKALE" },
  { pair: "GMXUSDT", ticker: "GMX", name: "GMX" },
  { pair: "KAVAUSDT", ticker: "KAVA", name: "Kava" },
  { pair: "MINAUSDT", ticker: "MINA", name: "Mina Protocol" },
  { pair: "ILVUSDT", ticker: "ILV", name: "Illuvium" },
  { pair: "CELOUSDT", ticker: "CELO", name: "Celo" },
  { pair: "ANKRUSDT", ticker: "ANKR", name: "Ankr" },
  { pair: "ENJUSDT", ticker: "ENJ", name: "Enjin Coin" },
  { pair: "CAKEUSDT", ticker: "CAKE", name: "PancakeSwap" },
  { pair: "ONEUSDT", ticker: "ONE", name: "Harmony" },
  { pair: "ZECUSDT", ticker: "ZEC", name: "Zcash" },
  { pair: "DASHUSDT", ticker: "DASH", name: "Dash" },
  { pair: "BATUSDT", ticker: "BAT", name: "Basic Attention Token" },
  { pair: "IOSTUSDT", ticker: "IOST", name: "IOST" },
  { pair: "ONTUSDT", ticker: "ONT", name: "Ontology" },
  { pair: "WAVESUSDT", ticker: "WAVES", name: "Waves" },
  { pair: "HOTUSDT", ticker: "HOT", name: "Holo" },
  { pair: "ICXUSDT", ticker: "ICX", name: "ICON" },
  { pair: "QTUMUSDT", ticker: "QTUM", name: "Qtum" },
  { pair: "ZRXUSDT", ticker: "ZRX", name: "0x" },
  { pair: "SUSHIUSDT", ticker: "SUSHI", name: "SushiSwap" },
  { pair: "YFIUSDT", ticker: "YFI", name: "yearn.finance" },
  { pair: "COTIUSDT", ticker: "COTI", name: "COTI" },
  { pair: "STORJUSDT", ticker: "STORJ", name: "Storj" },
  { pair: "CELRUSDT", ticker: "CELR", name: "Celer Network" },
  { pair: "RSRUSDT", ticker: "RSR", name: "Reserve Rights" },
  { pair: "RVNUSDT", ticker: "RVN", name: "Ravencoin" },
  { pair: "CHRUSDT", ticker: "CHR", name: "Chromia" },
  { pair: "REEFUSDT", ticker: "REEF", name: "Reef" },
  { pair: "DENTUSDT", ticker: "DENT", name: "Dent" },
  { pair: "MTLUSDT", ticker: "MTL", name: "Metal DAO" },
  { pair: "STMXUSDT", ticker: "STMX", name: "StormX" },
  { pair: "OGNUSDT", ticker: "OGN", name: "Origin Protocol" },
  { pair: "NMRUSDT", ticker: "NMR", name: "Numeraire" },
  { pair: "ARPAUSDT", ticker: "ARPA", name: "ARPA" },
  { pair: "CTSIUSDT", ticker: "CTSI", name: "Cartesi" },
  { pair: "BANDUSDT", ticker: "BAND", name: "Band Protocol" },
  { pair: "TRBUSDT", ticker: "TRB", name: "Tellor" },
  { pair: "RLCUSDT", ticker: "RLC", name: "iExec RLC" },
  { pair: "HBARUSDT", ticker: "HBAR", name: "Hedera" },
  { pair: "MASKUSDT", ticker: "MASK", name: "Mask Network" },
  { pair: "ACHUSDT", ticker: "ACH", name: "Alchemy Pay" },
  { pair: "ARUSDT", ticker: "AR", name: "Arweave" },
  { pair: "BLURUSDT", ticker: "BLUR", name: "Blur" },
  { pair: "KASUSDT", ticker: "KAS", name: "Kaspa" },
  { pair: "ORDIUSDT", ticker: "ORDI", name: "ORDI" },
  { pair: "WUSDT", ticker: "W", name: "Wormhole" },
  { pair: "PIXELUSDT", ticker: "PIXEL", name: "Pixels" },
  { pair: "STRKUSDT", ticker: "STRK", name: "Starknet" },
  { pair: "MANTAUSDT", ticker: "MANTA", name: "Manta Network" },
  { pair: "ALTUSDT", ticker: "ALT", name: "AltLayer" },
  { pair: "DYMUSDT", ticker: "DYM", name: "Dymension" },
  { pair: "ZETAUSDT", ticker: "ZETA", name: "ZetaChain" },
  { pair: "PORTALUSDT", ticker: "PORTAL", name: "Portal" },
  { pair: "PYTHUSDT", ticker: "PYTH", name: "Pyth Network" },
  { pair: "JTOUSDT", ticker: "JTO", name: "Jito" },
  { pair: "ACEUSDT", ticker: "ACE", name: "Fusionist" },
  { pair: "NFPUSDT", ticker: "NFP", name: "NFPrompt" },
  { pair: "XAIUSDT", ticker: "XAI", name: "Xai" },
  { pair: "AIUSDT", ticker: "AI", name: "Sleepless AI" },
  { pair: "MOVEUSDT", ticker: "MOVE", name: "Movement" },
  { pair: "MEUSDT", ticker: "ME", name: "Magic Eden" },
  { pair: "VANAUSDT", ticker: "VANA", name: "Vana" },
  { pair: "PENGUUSDT", ticker: "PENGU", name: "Pudgy Penguins" },
  { pair: "USUALUSDT", ticker: "USUAL", name: "Usual" },
  { pair: "BIOUSDT", ticker: "BIO", name: "BIO Protocol" },
  { pair: "COOKIEUSDT", ticker: "COOKIE", name: "Cookie DAO" },
  { pair: "TRUMPUSDT", ticker: "TRUMP", name: "Official Trump" },
  { pair: "TWTUSDT", ticker: "TWT", name: "Trust Wallet Token" },
  { pair: "CKBUSDT", ticker: "CKB", name: "Nervos Network" },
  { pair: "JASMYUSDT", ticker: "JASMY", name: "JasmyCoin" },
  { pair: "POWRUSDT", ticker: "POWR", name: "Powerledger" },
  { pair: "SUPERUSDT", ticker: "SUPER", name: "SuperVerse" },
  { pair: "LEVERUSDT", ticker: "LEVER", name: "LeverFi" },
  { pair: "EDUUSDT", ticker: "EDU", name: "Open Campus" },
  { pair: "BEAMUSDT", ticker: "BEAM", name: "Beam" },
  { pair: "ROSEUSDT", ticker: "ROSE", name: "Oasis Network" },
  { pair: "LPTUSDT", ticker: "LPT", name: "Livepeer" },
  { pair: "SCUSDT", ticker: "SC", name: "Siacoin" },
  { pair: "GMTUSDT", ticker: "GMT", name: "GMT" },
  { pair: "API3USDT", ticker: "API3", name: "API3" },
  { pair: "HIGHUSDT", ticker: "HIGH", name: "Highstreet" },
  { pair: "TRUUSDT", ticker: "TRU", name: "TrueFi" },
  { pair: "LSKUSDT", ticker: "LSK", name: "Lisk" },
  { pair: "SSVUSDT", ticker: "SSV", name: "ssv.network" },
  { pair: "BAKEUSDT", ticker: "BAKE", name: "BakeryToken" },
  { pair: "WAXPUSDT", ticker: "WAXP", name: "WAX" },
  { pair: "GLMUSDT", ticker: "GLM", name: "Golem" },
  { pair: "NKNUSDT", ticker: "NKN", name: "NKN" },
  { pair: "IOTXUSDT", ticker: "IOTX", name: "IoTeX" },
  { pair: "SFPUSDT", ticker: "SFP", name: "SafePal" },
  { pair: "PHBUSDT", ticker: "PHB", name: "Phoenix" },
  { pair: "LITUSDT", ticker: "LIT", name: "Litentry" },
  { pair: "FIDAUSDT", ticker: "FIDA", name: "Bonfida" },
  { pair: "HARDUSDT", ticker: "HARD", name: "HARD Protocol" },
  { pair: "ALPACAUSDT", ticker: "ALPACA", name: "Alpaca Finance" },
  { pair: "OMUSDT", ticker: "OM", name: "MANTRA" },
  { pair: "THETAUSDT", ticker: "THETA", name: "Theta Network" },
  { pair: "RADUSDT", ticker: "RAD", name: "Radicle" },
  { pair: "XVSUSDT", ticker: "XVS", name: "Venus" },
  { pair: "PROSUSDT", ticker: "PROS", name: "Prosper" },
  { pair: "VIBUSDT", ticker: "VIB", name: "Viberate" },
  { pair: "WINGUSDT", ticker: "WING", name: "Wing Finance" },
  { pair: "FORTHUSDT", ticker: "FORTH", name: "Ampleforth Governance" },
  { pair: "POLYXUSDT", ticker: "POLYX", name: "Polymesh" },
  { pair: "GASUSDT", ticker: "GAS", name: "Gas" },
  { pair: "GLMRUSDT", ticker: "GLMR", name: "Moonbeam" },
  { pair: "AGLDUSDT", ticker: "AGLD", name: "Adventure Gold" },
  { pair: "COMBOUSDT", ticker: "COMBO", name: "Furucombo" },
  { pair: "MAVUSDT", ticker: "MAV", name: "Maverick Protocol" },
  { pair: "ARKMUSDT", ticker: "ARKM", name: "Arkham" },
  { pair: "CYBERUSDT", ticker: "CYBER", name: "CyberConnect" },
  { pair: "IDUSDT", ticker: "ID", name: "SPACE ID" },
  { pair: "RDNTUSDT", ticker: "RDNT", name: "Radiant Capital" },
  { pair: "HOOKUSDT", ticker: "HOOK", name: "Hooked Protocol" },
  { pair: "MAGICUSDT", ticker: "MAGIC", name: "MAGIC" },
  { pair: "TUSDT", ticker: "T", name: "Threshold" },
  { pair: "AMBUSDT", ticker: "AMB", name: "AirDAO" },
  { pair: "LOOMUSDT", ticker: "LOOM", name: "Loom Network" },
];

// Get coin logo URL from CoinCap CDN
// CoinGecko large logos (CORS-friendly, high-res)
const CG: Record<string, string> = {
  BTC: "1/large/bitcoin.png",
  ETH: "279/large/ethereum.png",
  SOL: "4128/large/solana.png",
  ADA: "975/large/cardano.png",
  DOT: "12171/large/polkadot.png",
  BCH: "780/large/bitcoin-cash-circle.png",
  QNT: "3370/large/5ZOu7brX_400x400.jpg",
  BNB: "825/large/bnb-icon2_2x.png",
  XRP: "44/large/xrp-symbol-white-128.png",
  DOGE: "5/large/dogecoin.png",
  AVAX: "12559/large/Avalanche_Circle_RedWhite_Trans.png",
  MATIC: "4713/large/polygon.png",
  LINK: "877/large/chainlink-new-logo.png",
  UNI: "12504/large/uni.jpg",
  SHIB: "11939/large/shiba.png",
  LTC: "2/large/litecoin.png",
  ATOM: "1481/large/cosmos_hub.png",
  FIL: "12817/large/filecoin.png",
  APT: "26455/large/aptos_round.png",
  NEAR: "10365/large/near.jpg",
  ARB: "16547/large/arb.jpg",
  OP: "25244/large/Optimism.png",
  SUI: "26375/large/sui-ocean-square.png",
  TRX: "1094/large/tron-logo.png",
  ETC: "453/large/ethereum-classic-logo.png",
  XLM: "100/large/Stellar_symbol_black_RGB.png",
  ALGO: "4380/large/download.png",
  HBAR: "3688/large/hbar.png",
  ICP: "14495/large/Internet_Computer_logo.png",
  VET: "3077/large/VeChain-Logo-768x725.png",
  FTM: "4001/large/Fantom_round.png",
  SAND: "12129/large/sandbox_logo.jpg",
  MANA: "878/large/decentraland-mana.png",
  AXS: "13029/large/axie_infinity_logo.png",
  AAVE: "12645/large/aave-token.png",
  GRT: "13397/large/Graph_Token.png",
  CRV: "12124/large/Curve.png",
  MKR: "1364/large/Mark_Maker.png",
  SNX: "3406/large/SNX.png",
  COMP: "10775/large/COMP.png",
  ENJ: "1102/large/enjin-coin-logo.png",
  PEPE: "33844/large/pepe.jpg",
  FLOKI: "10947/large/Floki_logo.png",
  INJ: "12882/large/Secondary_Symbol.png",
  TIA: "31967/large/tia.jpg",
  SEI: "28205/large/Sei_Logo_-_Transparent.png",
  STX: "2069/large/Stacks_logo_full.png",
  IMX: "17233/large/immutableX-symbol-BLK-RGB.png",
  RNDR: "11636/large/rndr.png",
  FET: "5681/large/Fetch.jpg",
  WLD: "31069/large/worldcoin.jpeg",
  RUNE: "6595/large/Rune200x200.png",
  EGLD: "12335/large/egld-token-logo.png",
  THETA: "2538/large/theta-token-logo.png",
  XTZ: "976/large/Tezos-logo.png",
  EOS: "738/large/eos-eos-logo.png",
  NEO: "480/large/NEO_512_512.png",
  IOTA: "692/large/IOTA_Swirl.png",
  CAKE: "12632/large/pancakeswap-cake-logo_%281%29.png",
  ZIL: "2469/large/zilliqa-logo.png",
  ONE: "4344/large/Y88JAze.png",
  KSM: "9568/large/m_kusama_logo.png",
  FLOW: "13446/large/5f6294c0c7a8cda55cb1c936_Flow_Wordmark.png",
  GALA: "12493/large/GALA-COINGECKO.png",
  CHZ: "8834/large/CHZ_Token_updated.png",
  LDO: "13573/large/Lido_DAO.png",
  RPL: "2848/large/Rocket_Pool_%28RPL%29.png",
  GMX: "18323/large/coingecko-gmx-200.png",
  DYDX: "28324/large/dYdX.png",
  BLUR: "28453/large/blur.png",
  APE: "24383/large/apecoin.jpg",
  CRO: "7310/large/cro_token_logo.png",
  KAVA: "6761/large/kava.png",
  ROSE: "13162/large/rose.png",
  ZEC: "486/large/circle-zcash-color.png",
  DASH: "19/large/dash-logo.png",
  XMR: "69/large/monero_logo.png",
  WAVES: "5252/large/WAVES.png",
  BAT: "677/large/basic-attention-token.png",
  ZRX: "863/large/0x.png",
  SUSHI: "12271/large/512x512_Logo_no_chop.png",
  YFI: "11849/large/yfi-192x192.png",
  BAL: "11683/large/Balancer.png",
  "1INCH": "13469/large/1inch-token.png",
  CELO: "11090/large/InjsF1VW_400x400.jpg",
  ANKR: "4956/large/Ankr_Logo_CoinGecko.png",
  MASK: "14051/large/masknetwork.png",
  WIF: "33566/large/dogwifhat.jpg",
  BONK: "28600/large/bonk.jpg",
  JUP: "34188/large/jup.png",
  PENDLE: "15069/large/Pendle_Logo_Normal-03.png",
  PYTH: "31924/large/pyth.png",
  POL: "4713/large/polygon.png",
  TAO: "28452/large/tao.png",
  TRUMP: "38028/large/trump.jpg",
};

export function getCoinLogoUrl(ticker: string): string {
  const t = ticker.toUpperCase();
  const path = CG[t];
  if (path) {
    return `https://assets.coingecko.com/coins/images/${path}`;
  }
  // Fallback: coincap (lower res but covers most coins)
  return `https://assets.coincap.io/assets/icons/${t.toLowerCase()}@2x.png`;
}

// Legacy lookups (still used by some components)
export const SYMBOL_LABELS: Record<Symbol, string> = {
  BTCUSDT: "Bitcoin",
  ETHUSDT: "Ethereum",
  SOLUSDT: "Solana",
  ADAUSDT: "Cardano",
  DOTUSDT: "Polkadot",
  BCHUSDT: "Bitcoin Cash",
  QNTUSDT: "Quant",
};

export const SYMBOL_TICKERS: Record<Symbol, string> = {
  BTCUSDT: "BTC",
  ETHUSDT: "ETH",
  SOLUSDT: "SOL",
  ADAUSDT: "ADA",
  DOTUSDT: "DOT",
  BCHUSDT: "BCH",
  QNTUSDT: "QNT",
};

export const SYMBOL_COLORS: Record<Symbol, string> = {
  BTCUSDT: "#F7931A",
  ETHUSDT: "#627EEA",
  SOLUSDT: "#9945FF",
  ADAUSDT: "#0033AD",
  DOTUSDT: "#E6007A",
  BCHUSDT: "#8DC351",
  QNTUSDT: "#000000",
};
